Feat/sort
programmers-Y2J/CROUP-frontEnd pull request #36
Opened 2024-07-07 19:01 UTC by namkijoo

### PR Type
<!— Please check the one that applies to this PR using "x". —>

- [ ] 버그수정(Bugfix)
- [x] 기능개발(Feature)
- [ ] 코드 스타일 변경(Code style update) (formatting, local variables)
- [ ] 리팩토링 (no functional changes, no api changes)
- [ ] 빌드 관련 변경
- [ ] 문서 내용 변경
- [ ] Other… Please describe:

### 요약(Summary)
분류기능, 검색기능 추가

### 상세 내용(Describe your changes)
분류기능(최신순, 인기순), 검색기능, 방생성시 태그 추가

### Issue Number or Link

2024-07-08 10:32 UTC, SebellKo reviewed
기주님 !
어쩌다보니 이번 리뷰는 유독 코멘트가 많네요..ㅎㅎ

궁금한 내용은 정말 궁금해서 여쭤본 질문이니 편하게 답변 부탁드려요 ~~

2024-07-08 10:32 UTC, SebellKo commented on src/components/Home/RoomListComponent.jsx
> +    if (response.roomList) {
기주님 !
API 명세에 방 검색하기에 response로 `roomList`가 포함되지 않았는데, `roomList`는 어떤 데이터 일까요 ?!

추가로 console.log()는 삭제해주셔도 될것 같아요 ~

2024-07-08 10:32 UTC, SebellKo commented on src/components/Home/RoomListComponent.jsx
> +    }
```
let setUrl = `/rooms/search?q=${search}&sort=${sortValue}`
if (search === '') setUrl = `/rooms?sort=${sortValue}`
```

위 처럼 else문을 생략하는건 어떠실까요 ?!

2024-07-08 10:32 UTC, SebellKo commented on src/components/Home/RoomListComponent.jsx
>  const RoomData = [
RoomData도 삭제해주셔도 될것 같아요 ~

2024-07-08 10:32 UTC, SebellKo commented on src/components/Home/RoomListComponent.jsx
> +  const { data, error } = useQuery(['rooms', search, selectValue], () => fetchRooms(apiRequest, search, selectValue));
인기순, 최신순 정렬과 검색 기능이 같이 이루어 지는건가요 ?!
그렇다면 각각 분리하는건 어떤가요 ?!

2024-07-08 10:32 UTC, SebellKo commented on src/components/Home/RoomListComponent.jsx
>    if (error) {
useQuery가 제공하는 `isError`를 사용하는건 어떠실까요 ?!

2024-07-08 10:32 UTC, SebellKo commented on src/components/Home/RoomListComponent.jsx
> +              tag={item.tags || 'tag'}
`'tag'`와 아래 `'sebell'`은 삭제해도 괜찮을것 같습니다 !!

2024-07-08 10:32 UTC, SebellKo commented on src/components/Modal/CreateRoom.jsx
> +    musicTitle: item.snippet.description,
여기 제목에 description이 들어가고 있습니다 !

2024-07-08 10:32 UTC, SebellKo commented on src/components/Modal/CreateRoom.jsx
> +      alert('플레이리스트를 불러오지 못했습니다.');
기주님 괜찮으시면 alert를 shadcn이 제공하는 alert 컴포넌트로 대체해주실 수 있을까요 ??
https://ui.shadcn.com/docs/components/alert

2024-07-08 10:32 UTC, SebellKo commented on src/stores/Auth/useUserStore.js
> +const useAuthStore = create((set) => ({
혹시 useUserStore의 스토어 이름은 useAuthStore인데 반해 useRoomStore의 파일 이름을 useAuthStore로 변경하신 이유가 있으신가요 ?!

2024-07-08 10:32 UTC, SebellKo commented on src/stores/Auth/useUserStore.js
> +    if (token) {
혹시 유저 정보를 로컬 스토리지에 추가로 저장하시는 이유가 있으신가요 ?!?!

2024-07-08 11:48 UTC, namkijoo commented on src/components/Home/RoomListComponent.jsx
> +    if (response.roomList) {
백엔드분들이 변경하셔서 그런건지 GET /rooms 했을때 roomList로 반환되고 search했을때는 rooms로 반환되더라고요.
console삭제했습니다!

2024-07-08 11:58 UTC, namkijoo commented on src/components/Home/RoomListComponent.jsx
> +    }
변경완료했습니다

2024-07-08 11:59 UTC, namkijoo commented on src/components/Home/RoomListComponent.jsx
>  const RoomData = [
삭제했습니다!

2024-07-08 12:03 UTC, namkijoo commented on src/components/Home/RoomListComponent.jsx
> +              tag={item.tags || 'tag'}
수정했습니다

2024-07-08 12:08 UTC, namkijoo commented on src/stores/Auth/useUserStore.js
> +const useAuthStore = create((set) => ({
헉 제가 실수로 변경한것같습니다. 돌려놓겠습니다

2024-07-08 12:12 UTC, namkijoo commented on src/stores/Auth/useUserStore.js
> +    if (token) {
전역상태로 관리할때 새로고침하면 데이터가 초기화되는걸로 알아서 로컬 스토리지에 저장했는데 필요없는 부분일까요?

2024-07-08 12:16 UTC, namkijoo commented on src/components/Home/RoomListComponent.jsx
>    if (error) {
넵 확인했습니다

2024-07-08 14:41 UTC, ksy90101 commented on src/components/Common/Header.jsx
> +      useAuthStore.getState().setToken(null);
useAuthStore에 clear같은걸 만들어서 처리하는게 더 좋을거 같아요.
밖에서 데이터를 변경하기 보단 hook에서 처리하는게 훨씬 더 코드 응집도가 높아지는거 같습니다.

2024-07-08 14:41 UTC, ksy90101 commented on src/components/Common/Header.jsx
> +      navigate('/login');
위의 조건이나 아래 조건 이나 똑같이 login으로 이동하니 이 조건 빼고 그냥 navigate를 해도 되겠는데요?

2024-07-08 14:41 UTC, ksy90101 commented on src/components/Home/RoomListComponent.jsx
> +// import { useNavigate } from 'react-router-dom';
주석은 안쓰이면 제거하는게 좋을거 같습니다.

2024-07-08 14:41 UTC, ksy90101 commented on src/components/Home/RoomListComponent.jsx
> +    });
api는 따로 빼두는게 좋습니다.

2024-07-08 14:41 UTC, ksy90101 commented on src/components/Home/RoomListComponent.jsx
> +    if (response.roomList) {
List보단 rooms가 더 어울리는거 같아요.

2024-07-08 14:41 UTC, ksy90101 commented on src/pages/Register.jsx
> +              />
이런 영역들을 컴포넌트로 만들어 둔다면 위의 로그인과 공통으로 처리할수 있을거 같기도 하네요.

2024-07-08 14:41 UTC, ksy90101 commented on src/stores/Auth/useUserStore.js
> +  nickname: null,
이건 API로 그냥 처리해도 될거 같아요.
react-query쓰면 캐싱도 될거구요.

2024-07-08 16:38 UTC, namkijoo commented on src/components/Home/RoomListComponent.jsx
> +  const { data, error } = useQuery(['rooms', search, selectValue], () => fetchRooms(apiRequest, search, selectValue));
검색했을때도 정렬기능을 사용할 수 있으니 그렇게 설정했는데 각각이 좋을까요?

2024-07-08 16:51 UTC, namkijoo commented on src/components/Common/Header.jsx
> +      useAuthStore.getState().setToken(null);
네 clear로 처리해보겠습니다

2024-07-08 16:51 UTC, namkijoo commented on src/components/Common/Header.jsx
> +      navigate('/login');
넵~

2024-07-08 16:51 UTC, namkijoo commented on src/components/Home/RoomListComponent.jsx
> +// import { useNavigate } from 'react-router-dom';
확인했습니다!

2024-07-08 16:51 UTC, namkijoo commented on src/components/Home/RoomListComponent.jsx
> +    if (response.roomList) {
넵 통일할 수 있도록 해보겠습니다

2024-07-08 16:54 UTC, namkijoo commented on src/stores/Auth/useUserStore.js
> +  nickname: null,
넵 감사합니다!

2024-07-08 16:54 UTC, namkijoo commented on src/pages/Register.jsx
> +              />
넵 확인했습니다

2024-07-08 17:00 UTC, namkijoo commented on src/components/Modal/CreateRoom.jsx
> +      alert('플레이리스트를 불러오지 못했습니다.');
넵

2024-07-09 13:47 UTC, SebellKo commented on src/stores/Auth/useUserStore.js
> +    if (token) {
zustand의 persist 를 사용하면 해결할 수 있을것 같습니다 !!
로컬스토리지에 저장하는건 같은 맥락이긴 합니다 !!

https://velog.io/@dpldpl/Zustand-persist-%ED%8E%98%EC%9D%B4%EC%A7%80-%EC%83%88%EB%A1%9C%EA%B3%A0%EC%B9%A8-%EC%8B%9C-%EC%A0%84%EC%97%AD%EC%83%81%ED%83%9C-%EC%B4%88%EA%B8%B0%ED%99%94-%EB%B0%A9%EC%A7%80-%EB%AC%B8%EC%A0%9C-%ED%95%B4%EA%B2%B0

2024-07-09 15:01 UTC, ksy90101 approved these changes
굿굿

2024-07-12 00:32 UTC, ksy90101 requested changes

2024-07-12 00:32 UTC, ksy90101 commented on src/components/Common/Header.jsx
> +    if (!isLoggedIn) {
이런 경우에 else if가 더어울릴거 같아요.
굳이 위의 조건에서 끝나고 또 이 코드가 실행될 필요가 없잖아요 ㅎㅎ

2024-07-12 00:32 UTC, ksy90101 approved these changes

2024-07-12 06:25 UTC, namkijoo commented on src/components/Common/Header.jsx
> +    if (!isLoggedIn) {
넵~

2024-07-12 10:39 UTC, merged